# Generated by Django 4.2 on 2024-12-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=55)),
                ('position', models.CharField(max_length=100)),
                ('Resume', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'jobtb',
            },
        ),
    ]
