# Generated by Django 4.2 on 2024-12-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='position',
            new_name='Position',
        ),
    ]
