# Generated by Django 4.2 on 2024-12-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0002_rename_position_jobmodel_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=400)),
                ('File', models.FileField(upload_to='usernes/')),
            ],
            options={
                'db_table': 'uploadtb',
            },
        ),
    ]
