# Generated by Django 4.2 on 2024-12-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0004_alter_uploadmodel_file_alter_uploadmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisemodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'advertisetb',
            },
        ),
    ]
