# Generated by Django 4.2 on 2024-12-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0005_advertisemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.TextField(max_length=200)),
                ('Message', models.TextField(max_length=400)),
            ],
            options={
                'db_table': 'contacttb',
            },
        ),
    ]
