# Generated by Django 4.2 on 2024-12-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0006_contactmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='Subject',
            new_name='Subjct',
        ),
    ]
