# Generated by Django 4.2 on 2024-12-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0007_rename_subject_contactmodel_subjct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='Subjct',
        ),
    ]
