# Generated by Django 4.2 on 2024-12-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0011_delete_carouselimage_delete_mainnews_delete_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtubenews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'youtubetb',
            },
        ),
    ]
