# Generated by Django 4.2 on 2024-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0012_youtubenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='bigimage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'bigimagetb',
            },
        ),
    ]
