# Generated by Django 4.2 on 2024-12-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0013_bigimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='videonews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('vido', models.FileField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'videotb',
            },
        ),
    ]
