# Generated by Django 4.2 on 2024-12-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0014_videonews'),
    ]

    operations = [
        migrations.CreateModel(
            name='bottomnews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='uploads/')),
                ('explain', models.CharField(max_length=400)),
                ('ytlink', models.URLField()),
            ],
            options={
                'db_table': 'bottomtb',
            },
        ),
    ]
