# Generated by Django 4.2 on 2024-12-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0016_youtubenews_ytlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigimage',
            name='ytlink',
            field=models.URLField(null=True),
        ),
    ]
