# Generated by Django 4.2 on 2024-12-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0017_bigimage_ytlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='chunavnews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='uploads/')),
                ('explain', models.CharField(max_length=400)),
                ('heading', models.CharField(max_length=100)),
                ('textfornews', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'chunavtb',
            },
        ),
    ]
