# Generated by Django 4.2 on 2024-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pratyakshapp', '0018_chunavnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='describenews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='uploads/')),
                ('textfornews', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'describe1tb',
            },
        ),
    ]
